### PR TITLE
InBuilt support for AT25XE041B

### PR DESCRIPTION
**Pull request by bakibakis**
Added support for new device AT25XE041B (Adesto - Atmel)

Tests passed - speeds are taken from tests.

### CODE REVIEW

**Comment by eblot** [comment]
Hi,

Thanks for the patch.

* Can you use a datasheet URL from the manufacturer rather than from a distributor (maybe https://www.adestotech.com/wp-content/uploads/DS-AT25XE041B_062.pdf, not sure).
* Use a generic device syntax for FTDI (`ftdi:///1`) so that no specific HW is defined

Thanks.

**Comment by eblot** [comment]
Can you have a look at https://github.com/eblot/pyspiflash/pull/20#issuecomment-729057705 Thanks

**Comment by bakibakis** [comment]
Sorry for the delay. I was really busy last days. Fixed according you feedback...

**Comment by eblot** [comment]
Merged, thanks.

I reverted the changes in the unit test, as I'm not sure they would not break with other flash devices.

**Pull request merged**
